#!/usr/bin/env node

var program = require('commander'),
	common = require('./common'),
	server = require('./server');

function parseOverride(string) {
	var options = {};
	var couplets = string.trim().split(',');
	for (var i = couplets.length - 1; i >= 0; i--) {
		var pair = couplets[i].split(':');
		if(pair.length !== 2) {
			console.error('malformed option `' + couplets[i] + '` : must be of form "option:value"');
			continue;
		}
		options[pair[0]] = pair[1];
	}

	return options;
}

program
	.usage('[config_file]')
	.option('-o, --overrides [options]', 'specify extra options, overrides the config file', parseOverride)
	.option('-p, --port [port_number]', 'Bind server to the specified port, overrides other configurations')
	.option('-V, --credits', 'Print software version and credits')
	.parse(process.argv);

var overrides = program.overrides || {};

if(program.credits) {
	console.info(common.about);
	process.exit(0);
}

if(program.port)
	overrides.port = parseInt(program.port, 10);

var server = server.createServer(program.args[0] || 'proxy.conf', overrides);
server.listen();